OTC-881: Product code uniqueness query and check.
openimis/openimis-be-product_py pull request #26
Opened 2023-02-10 09:19 UTC by wzglinieckisoldevelo

https://openimis.atlassian.net/browse/OTC-881

Changes:
- Added query for checking of the uniqueness of the product code
- Backend now blocks saving if code is not unique
- Query checks for user permission before responding

2023-02-10 09:25 UTC, malinowskikam requested changes
Please chekc out my comments

2023-02-10 09:25 UTC, malinowskikam commented on product/gql_mutations.py
> +    current_product = Product.objects.filter(uuid=product_uuid)
You are missing .first() here

```suggestion
    current_product = Product.objects.filter(uuid=product_uuid).first()
```

2023-02-10 09:25 UTC, malinowskikam commented on product/services.py
> +    from .models import Product
You can import that at the top of that's the same module

2023-02-10 09:53 UTC, malinowskikam approved these changes
Looks good to me

2023-02-14 12:48 UTC, delcroip approved these changes

2023-02-14 12:48 UTC, merged